### ISSUE TITLE
Latest github action workflow interrupted?

### ISSUE THREAD

**Issue by kevinrue** [systemPipeR/systemPipeWorkshop2021#1]
It looks like the latest github action workflow was cancelled halfway through:
https://github.com/systemPipeR/systemPipeWorkshop2021/runs/3226447329

I just wanted to check whether this was intentional or not, as it means that the docker image hasn't been built for the latest push.

**Comment by dcassol** [comment]
Hi Kevin, 
yes, that was intentional. I just push again, for a new build. :)

**Comment by kevinrue** [comment]
OK - i just saw your status badge going red on my little dashboard ;)
